apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: egs-eventfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.deti:5000/egs-eventfinder/webapp:v10
          env:
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: "true"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80  # Updated the container port to 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: egs-eventfinder
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80  # Updated the port to 80
      targetPort: 80  # Updated the target port to 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: egs-eventfinder
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: webappfinder.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
