apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: egs-eventfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.deti:5000/egs-eventfinder/app:v1
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
